version: '3'

tasks:
  default:
    cmds:
      - task: backend

  backend:
    description: Run backend server.
    dir: backend
    cmds:
      - go run main.go
    silent: true

  frontend:
    description: Run frontend development server.
    dir: frontend
    cmds:
      - pnpm run dev
    silent: true
